### PR TITLE
Sum lazy variables

### PR DESCRIPTION
**Pull request by gpleiss**
They're finally here.

The posterior calculations (`exact_posterior_alpha`, etc.) have been refactored into new strategy objects.

### CODE REVIEW

**Comment by gpleiss** [comment]
@jrg365 @wrh14

**Comment by gpleiss** [comment]
Since you guys aren't working on any similar features at the moment, let's leave this PR open for a while. I'm going to play around with it in action and make sure there's nothing else to add.

**Comment by gpleiss** [comment]
Sum lazy variables appear to be successful, so this PR is ready for review/merge.

**Comment by jrg365** [comment]
Could you just check out the failing test on Travis before merging? It's in `getitem`, so it looks like it's not a usual numerical precision failure.

**Comment by gpleiss** [comment]
Fixed the flaky test, so merging

**Pull request merged**
